### ISSUE TITLE
CSP policy prevents some admin pages from loading properly

### ISSUE THREAD

**Issue by nick-lehmann** [CupCakeArmy/liquet#1]
When the `liquet` theme is activated at the site that is not `nicco.io`, the loading of many scripts is blocked by the content security policy.

![Screenshot 2020-01-07 at 14 36 48](https://user-images.githubusercontent.com/2708875/71899049-3178b280-315b-11ea-9f8d-f4a05e8d13c4.png)

In the server logs I can see a batch of requests that look like this

```
10.244.0.102 - - [07/Jan/2020:13:31:45 +0000] "POST /wp-admin/csp@nicco.io HTTP/1.1" 302 -
```

Seems like the endpoint is geard towards your domain and does not change when the theme is deployed to another domain.

**Comment by nick-lehmann** [comment]
While I thought only the required plugins, there were also Jetpack and Askimet installed. Those are the only two I installed after activating `liquet`. For some strange reason, deactivting them and setting them up again solved the issue for now. Will keep an eye on it.

**Comment by cupcakearmy** [comment]
Should be fixed in v0.15

**Comment by nick-lehmann** [comment]
Unfortunately, the issue was not solved. After updating liquet to version 0.15 and redeploying, the admin site for `posts` and `pages` are broken and the same errors appear. Maybe [this](https://wordpress.org/support/topic/content-security-policy-error-after-upgrading-to-https-on-wordpress-site/) helps.

Same as before, if I change the theme to a default one, the issue disappears.
